include: 
   - ["_pages"]
   - ["_posts"]


collections:
  wiki:
    output: true
    permalink: /:collection/:path/

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true


